development:
  adapter: async

   url: redis://redistogo:5c56b4819a8289d30faa720ca4b83350@tarpon.redistogo.com:10098/


test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: realtime_production
